version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout

  rotating_file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: DEBUG
    filename: log/powerbi_api.log
    maxBytes: 5242880  # 5 MB
    backupCount: 5
    encoding: utf8

loggers:
  my_logger:
    level: DEBUG
    handlers: [console, rotating_file]
    propagate: no

root:
  level: INFO
  handlers: [console, rotating_file]